twist_mux:
  ros__parameters:
    topics:
      joy:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 10
      keyboard:
        topic   : cmd_vel
        timeout : 0.5
        priority: 15
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 20
    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255